version: "3.9"

services:
  sushi-polygon-ema:
    container_name: sushi-polygon-ema
    image: ghcr.io/tradingstrategy-ai/trade-executor:${TRADE_EXECUTOR_VERSION}
    volumes:
      # Map the path from where we load the strategy Python modules
      - ./strategy:/usr/src/trade-executor/strategy
      # Save the strategy execution state in the local filesystem
      - ./state:/usr/src/trade-executor/state
      # Cache the dataset downloads in the local filesystem
      - ./cache:/usr/src/trade-executor/cache
      # Save the log files to the local file system
      - ./logs:/usr/src/trade-executor/logs    
    ports:
      - "127.0.0.1:20234:3456"
    env_file:
      - ./secrets/sushi.env
    restart: unless-stopped
    mem_swappiness: 0
    command: start
